### ISSUE TITLE
Sort strategies by allocation percentage

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#10]
<img width="914" alt="Screen Shot 2022-12-01 at 7 47 01 AM" src="https://user-images.githubusercontent.com/273937/205097072-9a128ae6-eb62-4549-8cc7-2554cae7174b.png">

**Comment by rolandpo** [comment]
done in 7386bf1d68e9748e9794bff41cf33f546a873ab0
