### ISSUE TITLE
OUSD blog cleanup

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/ousd.com#11]
Designs for both the blog home page and article page. Both Desktop and mobile

https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=2047%3A25408&t=bao4792JxacOHP0r-1

There's a hover state for the blog post cards here (outline changes transparency and background shadow both dissolve in with 'ease-in'): https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=2047%3A25406&t=bao4792JxacOHP0r-1

**Comment by rolandpo** [comment]
this should be done, lmk if there's any issues @matt-bullock

**Comment by rolandpo** [comment]
@matt-bullock good to close?

**Comment by matt-bullock** [comment]
@rolandpo Left some notes here with the most recent designs. Let make sure marketing are happy with it before making those updates https://docs.google.com/document/d/1Jq5FKCpyY7yLddkzSoNTZTaRncZMr8SMTDmyg0vCjhw/edit

**Comment by rolandpo** [comment]
closing for now, let me know if anything pops up
