### ISSUE TITLE
Point the OETH homepage to the dapp

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#148]
Once OETH has been audited and thoroughly tested, we will link to the dapp from the homepage in various places. We could either go ahead and set an environment variable to conditionally change code that we have in place ahead of time or we could just have a PR ready to go with the dapp links and deploy it when we're ready for usage.

**Comment by rafaelugolini** [comment]
We should have code ready to deploy before the time.

**Comment by micahalcorn** [comment]
Just making a note so that we don't forget, be sure to include the footer link (gated by env var) and then we can close this one @HrikB.

**Comment by HrikB** [comment]
Yup... the footer link is also tied to the envvar now.
