### ISSUE TITLE
Move Fullstory from OUSD to OETH

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#159]
Disable the [Fullstory](https://www.fullstory.com/) integration on OUSD.com and enable it on OETH.com so that we can capture a sample of user sessions and identify issues with our funnel.

**Comment by jonathansnow** [comment]
The integration on OUSD.com is disabled and removed.

Fullstory is implemented via GTM for basic tracking. This is limited to `www.oeth.com` and `app.oeth.com` within Fullstory, ensuring that we are not capturing dev sessions or wasting our 1000-session monthly limit.

We cannot test this until May 10th, when the plan resets, but it appears to be firing properly from within GTM.

```
Once you've hit your session and event session limit, data capture within FullStory will be paused until your next cycle. Before this happens though, we'll send an email notification to all account Admins as well as display a message within the UI for all users so that your team is aware. Once data capture is paused, you'll still be able to login and access previously captured sessions but no new sessions will be captured during this time period. 

Resets May 09, 2023, PDT at 8:00 PM
```

**Comment by micahalcorn** [comment]
> The integration on OUSD.com is disabled and removed.
> 
> Fullstory is implemented via GTM for basic tracking. This is limited to `www.oeth.com` and `app.oeth.com` within Fullstory, ensuring that we are not capturing dev sessions or wasting our 1000-session monthly limit.
> 
> We cannot test this until May 10th, when the plan resets, but it appears to be firing properly from within GTM.

Perfect, thanks.
