### ISSUE TITLE
Missing APY chart

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#165]
<img width="1393" alt="Screenshot 2023-05-03 at 6 34 21 AM" src="https://user-images.githubusercontent.com/273937/235931756-4d326bb1-2b4f-4dc3-b25c-13733f89a652.png">

**Comment by rafaelugolini** [comment]
This will be fixed when ousd analytics gets fully deployed.

**Comment by rafaelugolini** [comment]
It's back :)
