### ISSUE TITLE
Updates to OGV Dashboard to include OETH

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/ousd.com#167]
- [ ] What should we do about the logo as it shares the same header as OUSD.com homepage
- [ ] Do we change Origin Dollar Governance to Origin DeFi Governance in the header?
- [ ] Additional text changes in green to include OETH

https://www.figma.com/file/vSFSxrKzRZYGpXkZKbHPcA/OGV-Dashboard?type=design&node-id=901%3A1998&t=WJch3BQdz1k0n6j3-1

**Comment by micahalcorn** [comment]
I've taken care of the text here but we'll want to change the logo. I'll make a separate issue for that.
