### ISSUE TITLE
Updates to Governance page to include OETH

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/ousd.com#168]
I've identified all the copy that needs updating here:

https://www.figma.com/file/JTVKy7SSwEvlUV94iDwDt8/Governance?type=design&node-id=501%3A7316&t=MX9jlGshP2z1XOlW-1

**Comment by micahalcorn** [comment]
I've taken care of the text here but we'll want to change the logo. I'll make a separate issue for that.
