### ISSUE TITLE
Decrease margins on OUSD Blog

### ISSUE THREAD

**Issue by rmcn15** [OriginProtocol/ousd.com#171]
The OUSD blog has wider margins than our other sites... by a wide margin. 

Blogs currently load as a column of text, which likely scares readers away and hurts time on page + click thru rates. 

See here for example: https://www.ousd.com/ogv-eth-curve-incentives 
The margins on OETH look good: https://www.oeth.com/introducing-origin-ether-oeth

**Comment by rmcn15** [comment]
@rafaelugolini bumping this issue. It should be pretty low lift and will have an impact on SEO rankings.

**Comment by rafaelugolini** [comment]
@micahalcorn should we add this to the next sprint?

**Comment by micahalcorn** [comment]
This turned out to be a zoom issue. The container size is similar to Medium, so we'll leave it alone. Removing the redundant back button also cleaned up the look a bit.
