### ISSUE TITLE
Skewed author image

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#19]
I think the uploaded image in this case is slightly wider than it is tall. It is rendered properly in the content manager but it gets squeezed on the blog post.

<img width="298" alt="Screen Shot 2022-12-06 at 1 46 45 PM" src="https://user-images.githubusercontent.com/273937/206030400-bfabf01e-996a-4ff1-a210-96e7a2f540d5.png">

**Comment by rolandpo** [comment]
fix in #20
