### ISSUE TITLE
Burn page broken

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#3]
https://www.ousd.com/burn seems to have lost its styling.

<img width="1512" alt="Screen Shot 2022-11-30 at 12 01 43 PM" src="https://user-images.githubusercontent.com/273937/204896735-0560864e-9a7d-4330-8c36-2352c20c7b6e.png">

**Comment by rolandpo** [comment]
formatting fixed, data fetching fix in #21
