### ISSUE TITLE
Better handling of invalid URLs

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd.com#4]
Currently accessing an invalid page like https://www.ousd.com/oops results in an error page "Application error: a client-side exception has occurred (see the browser console for more information)."

Let's implement a better looking error page

**Comment by micahalcorn** [comment]
This is blocked by https://github.com/orgs/OriginProtocol/projects/4/views/7.

**Comment by micahalcorn** [comment]
This is blocked by https://github.com/OriginProtocol/origin-dollar/issues/1187.

**Comment by matt-bullock** [comment]
I put some options together here https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=2354%3A23875&t=OsuoqQtUUJlgdBBH-1

Let me know if there's a style you prefer and I'll set that up across the 3 sites
