### ISSUE TITLE
Why so high section

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#48]
We'd like to add a section to the homepage cutting to the chase about why our APY is higher than the underlying strategies. Here's the design in Figma:

https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=2760%3A24798&t=0FBKKJKpbxTPCJMh-4

The diagram on the right should just be a static image. There's no need to build it with HTML elements. We should confirm though with @matt-bullock that it will work on small screens in its current form.

I'm a little concerned that this jumps straight into a dense feature before a first-time visitor has a chance to understand more generally "how it works". In that case, we might put something else here and then move the secret sauce to a dedicated page where we have more room to explain it. For now, let's try just adding it as a section between the APY and the strategy allocations.

<img width="708" alt="Screen Shot 2023-01-19 at 7 30 54 PM" src="https://user-images.githubusercontent.com/273937/213617758-f84c4883-bc7b-46a1-b7fd-6891aff26ee0.png">

**Comment by franckc** [comment]
@HrikB Could you take a look at this feature request? Thanks! :)

**Comment by matt-bullock** [comment]
The image looks very pixelated. Is there a way to not compress the png image?

**Comment by HrikB** [comment]
Yeah I see that, looks like the `Image` component I was using has some optimizations that compress the image. Anyways, I turned it off so looks much better.
