### ISSUE TITLE
Missing canonical link on ousd.com

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd.com#49]
No canonical link from http://www.ousd.com/ to https://www.ousd.com/
There should be `<link rel="canonical" href="https://www.ousd.com/">` in the `<head>` section of the page.

Same with:
https://www.ousd.com/burn

Overall ideally we should have a canonical link on all the pages.

**Comment by franckc** [comment]
@rolandpo Do you mind taking a look at this issue? It impacts SEO so marketing flagged it as high priority for them. Thank you!

**Comment by rolandpo** [comment]
PR #51

**Comment by jansammut** [comment]
Hi, it seems that this tag has been added within a script tag, not the <head>
![image](https://user-images.githubusercontent.com/111856658/214360738-7ad0827c-79c3-47a0-b3c9-f3eaf1fb2bee.png)
![image](https://user-images.githubusercontent.com/111856658/214360837-546ecd59-8dd8-49b0-a2d0-e7b240609ea7.png)

**Comment by rolandpo** [comment]
ah I think the new code might not have been deployed to production yet actually

**Comment by jansammut** [comment]
Got it, thanks.
