### ISSUE TITLE
Frozen APY chart

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#5]
On seemingly random occasions, the graph doesn't update when the moving average selection is changed. Last time I experienced this, I noticed some CORS-related issues coming from the analytics API.

<img width="1511" alt="Screen Shot 2022-11-30 at 2 29 47 PM" src="https://user-images.githubusercontent.com/273937/204922349-87681381-5eeb-42d9-9cf0-2b02bf3a8478.png">

**Comment by franckc** [comment]
This is intermittent. So I don't understand why CORS would block the requests some times but not others?

But regardless, looking at Google App Engine I see a clear pattern of 500 errors on the analytics stack:
<img width="1054" alt="Screen Shot 2022-11-30 at 7 11 04 PM" src="https://user-images.githubusercontent.com/945910/204957082-1265e609-c5b6-498d-9a28-46c6259b3ea0.png">

Also note that the requests are cached by Cloudflare for 120sec (that's what the server set the Max-Age header to).
If there wouldn't be caching, the error rate might be even higher.

**Comment by franckc** [comment]
@shahthepro or @sparrowDom Could you please take a look?

**Comment by sparrowDom** [comment]
In the last 6 hours all of those errors were 503 so related to this issue: 
https://github.com/OriginProtocol/ousd-analytics/issues/254

**Comment by sparrowDom** [comment]
This PR addresses it: https://github.com/OriginProtocol/ousd-analytics/pull/256

**Comment by sparrowDom** [comment]
Fixed via https://github.com/OriginProtocol/ousd-analytics/pull/256 & https://github.com/OriginProtocol/ousd-analytics/pull/257
