### ISSUE TITLE
Navigating to Dashboard from Homepage bug

### ISSUE THREAD

**Issue by HrikB** [OriginProtocol/ousd.com#53]
OGV Allocation section is supposed to look like this:
![image](https://user-images.githubusercontent.com/23041116/213939398-3c8741ea-1ee4-481c-94f8-81200ffd0343.png)

But for some reason, when you arrive at the dashboard from the homepage, using the link in the footer, it looks like this:
![image](https://user-images.githubusercontent.com/23041116/213939356-0f49d8b2-f3e2-4ea5-a0d7-0d3273d29330.png)

**Comment by micahalcorn** [comment]
Probably not related, but it would be nice to fix https://github.com/OriginProtocol/ousd.com/issues/57 too.
