### ISSUE TITLE
Update OGV link in nav

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#55]
The OGV link in the footer has been updated to point to the new token dashboard, but the one in the nav has not. They should both point to the same place.

**Comment by shahthepro** [comment]
I have updated it on the CMS, the changes should reflect shortly

**Comment by micahalcorn** [comment]
> I have updated it on the CMS, the changes should reflect shortly

If I click the one in the nav, it fails silently:

<img width="609" alt="Screen Shot 2023-01-23 at 7 54 56 AM" src="https://user-images.githubusercontent.com/273937/214085937-2f352d2d-dccc-491f-8f24-790427831134.png">

**Comment by HrikB** [comment]
Also getting this problem on the `/blog` and `/ogv-dashboard` route:

![image](https://user-images.githubusercontent.com/23041116/214089858-85cd9227-4459-450d-b226-2267a7247249.png)

However, I was able to suppress the issue by changing the target from `_self` to `_parent` manually during server-side phase. Not sure what is going on with the `/blog` route though.

![image](https://user-images.githubusercontent.com/23041116/214090308-9260abb4-708f-4806-b9fd-58a028ce8507.png)
