### ISSUE TITLE
Add supply tooltips on mobile

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#58]
These help icons and associated tooltips are not included on small screens.

<img width="601" alt="Screen Shot 2023-01-23 at 7 59 04 AM" src="https://user-images.githubusercontent.com/273937/214087019-bb2edca5-0726-4bfe-bb9e-fc1bdd481112.png">

**Comment by HrikB** [comment]
Can I get a figma design on how this should show up on small screens? Wasn't sure how to implement it.
