### ISSUE TITLE
Broken burn page styling

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#59]
It looks like some of the OGV dashboard changes cause some side effects for the burn page (primarily line-height).

<img width="1512" alt="Screen Shot 2023-01-23 at 12 01 39 PM" src="https://user-images.githubusercontent.com/273937/214138244-242cca11-e015-4851-9ce6-6114ed5612ed.png">

**Comment by HrikB** [comment]
Very interesting issue... seems like adding typescript support allowed the default style provided by the `Typography.H3` from the storybook repo to actually be applied overriding the styles applied by `className`. Anyways, I added an `!important` to it so it should revert to original functionality.
