### ISSUE TITLE
Add Curve to the list of places where you can buy OGV

### ISSUE THREAD

**Issue by joshfraser** [OriginProtocol/ousd.com#69]
https://curve.fi/#/ethereum/pools/factory-crypto-205/swap

We could also include 1inch or other aggregators if we wanted to make it more balanced.

**Comment by micahalcorn** [comment]
@matt-bullock want to figure out how this fits into the homepage and the OGV dashboard? We'll need a clean version of their logo.

**Comment by matt-bullock** [comment]
Let's get the curve logo in here. Whilst we're looking at this section can we get the 'view dashboard' button in and link to the OGV dashboard. The background color of this section has changed to blue on the live site. Can we change it back to the purple shown in the screenshot here.

Mobile and desktop designs here: https://www.figma.com/file/XkS37DmHFHdlKrO2AeyhuE/OUSD-Marketing-Site?node-id=298%3A1295&t=xHdve23x1Z6KUdXJ-1

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/39496225/217867749-4ccb1256-009d-4aca-aa87-76a3edb45b0c.png">

On the OGV dashboard put the logo and link in here 

Mobile and desktop designs here: https://www.figma.com/file/vSFSxrKzRZYGpXkZKbHPcA/OGV-Dashboard?node-id=1%3A627&t=4MMeGuWM2UyJ9grR-1

<img width="958" alt="image" src="https://user-images.githubusercontent.com/39496225/217869052-891500f0-a5de-4a1f-9d72-d3d0533d336c.png">
