### ISSUE TITLE
Blog content formatting is broken

### ISSUE THREAD

**Issue by franckc** [OriginProtocol/ousd.com#7]
As reported by Ryan: in-article paragraph spacing, headings, and bullets aren't being recognized once published: https://www.ousd.com/how-to-earn-yield-on-stablecoins

**Comment by franckc** [comment]
CC @micahalcorn

**Comment by franckc** [comment]
From @nickick : to fix we'll want to add something like this, which adds those styles in originprotocol.com - https://github.com/OriginProtocol/website-frontend/blob/main/src/styles/Article.module.css

**Comment by rolandpo** [comment]
fixed
