### ISSUE TITLE
Update secret sauce section

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/ousd.com#78]
<img width="828" alt="How it works diagram - desktop" src="https://user-images.githubusercontent.com/39496225/218123155-f404974f-0de0-41ad-b596-7cc3828b53a9.png">
<img width="349" alt="How it works diagram - mobile" src="https://user-images.githubusercontent.com/39496225/218123163-54028e29-aca9-41e9-93af-649e480636d0.png">

**Comment by micahalcorn** [comment]
Let's also update the text on the left and tweak the layout. I'll provide details in Figma.

**Comment by HrikB** [comment]
@micahalcorn Do you have to figma link to the details?
