### ISSUE TITLE
At the shown breakpoint the strategies look misaligned. Convex OUSD+3Crv & Morpho Compound USDT should be left aligned

### ISSUE THREAD

**Issue by matt-bullock** [OriginProtocol/ousd.com#85]
<img width="978" alt="image" src="https://user-images.githubusercontent.com/39496225/220139147-312bf729-1dab-41b7-9cdd-a157e297c673.png">

**Comment by rolandpo** [comment]
pending PR for this in #74, or also covered in refactor in #80

**Comment by matt-bullock** [comment]
Ok great. I'll close this ticket then
