### ISSUE TITLE
Global pool allocation percentages

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#88]
On the allocation section of our homepage, we currently show each pool's allocation as a percentage of its parent protocol. I'm recommending that we change this to be percentages of the total allocation. It's alarming to breeze through this section and see a number that is nearly 100% for anything. It takes some cognitive effort to realize that this is saying nearly 100% of 69%, for example. It's easier to read exactly what the overall allocation is to a given pool rather than what its allocation is relative to similar pools within the same protocol.

<img width="1136" alt="Screenshot 2023-02-22 at 8 48 02 AM" src="https://user-images.githubusercontent.com/273937/220698624-0a40c2a3-b735-4a00-819c-25662a298446.png">

**Limited spec**
These numbers should change as follows:
- [ ] Aave DAI: 0.12%
- [ ] Aave USDC: 0.11%
- [ ] Aave USDT: 0.43%

<img width="1136" alt="Screenshot 2023-02-22 at 8 58 16 AM" src="https://user-images.githubusercontent.com/273937/220700937-1e213b93-50a9-4db6-bdac-caa94faf3148.png">

**Comment by DanielVF** [comment]
Strong agree

**Comment by rolandpo** [comment]
add to #80
