### ISSUE TITLE
Improve meta content for OGV dashboard

### ISSUE THREAD

**Issue by micahalcorn** [OriginProtocol/ousd.com#97]
When https://www.ousd.com/ogv-dashboard is shared, the preview content is not great. We should have a banner image as we have for the homepage along with a title and description that make sense. If it's practical to have distinct content from the homepage, let's do that. If not, let's get the same content to show up.

Preferred content:

**Title**
OGV Dashboard

**Description**
OGV is the governance and value accrual token for OUSD. Voters lock their OGV to earn fees from the growth of OUSD and participate in decentralized governance.

<img width="1007" alt="Screenshot 2023-03-03 at 9 00 11 AM" src="https://user-images.githubusercontent.com/273937/222781318-bc2aeb15-b2ca-4b20-b5ec-e265b7b6410f.png">

**Comment by franckc** [comment]
@micahalcorn What is the tool you made the screenshot from?

**Comment by micahalcorn** [comment]
> @micahalcorn What is the tool you made the screenshot from?

https://developers.facebook.com/tools/debug/
